Update README.md
zengxianyu/crfill pull request #11
Opened 2021-11-16 07:40 UTC by CVStack

Typo

2021-11-16 17:03 UTC, zengxianyu approved these changes

2021-11-16 17:07 UTC, zengxianyu requested changes
I do not wish to delete my logger module

2021-11-16 17:09 UTC, zengxianyu requested changes
I'd rather keep the logger as a standalone submodule

2021-11-18 04:42 UTC, CVStack commented
Oh, I'm sorry.

I didn't know it was sending the pull request about logger.

2021-11-18 04:45 UTC, closed without merging